parameters:
    event_append_subscriber_class: Chgst\ChgstBundle\EventListener\EventAppendSubscriber

services:

    Chgst\Command\HandlerInterface:
        public: true
        class: Chgst\Command\Handler
        arguments: [ '@event_dispatcher', '@Chgst\Event\RepositoryInterface']

    Chgst\Communication\CommandBusInterface:
        public: true
        class: Chgst\Communication\InMemoryCommandBus
        calls:
            - { method: 'setHandler', arguments: [ '@Chgst\Command\HandlerInterface' ]}

    Chgst\Communication\EventBusInterface:
        public: true
        autowire: true
        class: Chgst\Communication\InMemoryEventBus

    Chgst\ChgstBundle\EventListener\EventAppendSubscriber:
        public: true
        autowire: true
        class: '%event_append_subscriber_class%'
        tags:
            - { name: kernel.event_subscriber }

    Chgst\ChgstBundle\Command\ReplayStreamCommand:
        class: Chgst\ChgstBundle\Command\ReplayStreamCommand
        arguments: ['@Chgst\Event\RepositoryInterface', '@Chgst\Communication\EventBusInterface']

        tags: [ 'console.command' ]
